# Generated by Django 3.0.6 on 2020-06-03 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('problem', models.CharField(max_length=25)),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
