# Generated by Django 3.0.6 on 2020-06-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportproblem',
            name='problem',
            field=models.TextField(max_length=25),
        ),
    ]
