# Generated by Django 3.0.6 on 2020-07-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0005_auto_20200708_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
