# Generated by Django 3.0.6 on 2020-07-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0006_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='showcase_image',
            field=models.ImageField(blank=True, upload_to='showcase_images/%Y/%m/%d'),
        ),
    ]
