# Generated by Django 3.0.6 on 2020-07-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0007_post_showcase_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, upload_to='comments/%Y/%m/%d'),
        ),
    ]
